### ISSUE TITLE
目标域微调之后测试出错

### ISSUE THREAD

**Issue by kuyedie520** [chenhao2345/ABMT#2]
你好，我想问一下，我在目标域微调过程中，微调过程40轮进行完了总会出现这个问题，就是微调完成后在测试模型的时候，但是有时候又不会出现能够正确测试，请问一下这是什么问题。大多数情况下都会出错。
RuntimeError: Error(s) in loading state_dict for DataParallel:
	size mismatch for module.classifier.weight: copying a param with shape torch.Size([840, 2048]) from checkpoint, the shape in current model is torch.Size([844, 2048]).
	size mismatch for module.classifier_max.weight: copying a param with shape torch.Size([840, 2048]) from checkpoint, the shape in current model is torch.Size([844, 2048]).

**Comment by chenhao2345** [comment]
你好，这是因为每个epoch里聚类的结果会不同，所以最后一个epoch和最优epoch的classifier的参数会有所不同。我已经更新了一下代码，把最优epoch的类num_ids存下来就不会出现这个问题了。请参考新的examples/ABMT_target_adaptation.py
