### ISSUE TITLE
尝试过两个分支都进行聚类吗？

### ISSUE THREAD

**Issue by kuyedie520** [chenhao2345/ABMT#5]
你好，想问一下你尝试过两个分支都去生成各自的伪标签，然后利用上下分支生成的两个伪标签进行跨分支的训练学习。由于你选择了在平均网络上面做聚类，计算的分类损失，我也尝试过在下分支做聚类。想问一下为什么不两个分支都分别产生伪标签呢？做过实验吗想问一下。感谢回复！

**Comment by chenhao2345** [comment]
你好，我并没有尝试过两个分支各自生成伪标签，因为两个分支生成的伪类的数量会不同，貌似用cross entropy loss时会有问题。

**Comment by kuyedie520** [comment]
是的，两个聚类的数量不同无法进行交叉熵损失，但是你是用的上分支的平均网络聚类生成的伪标签与下分支网络做的分类损失，可以在对下分支做一个聚类与上分支做交叉熵损失。尝试过吗？

**Comment by kuyedie520** [comment]
之前尝试用了两个分支都进行聚类，然后代码遇到一些问题不知道怎么解决。

**Comment by chenhao2345** [comment]
用平均网络生成伪标签，是因为平均网络比较稳定，平均网络的表征质量也比较好。文章中的方式是想把更强的平均网络的知识蒸馏到学生网络中，学生网络表征质量比较差，所以我没试过再把学生网络做一个聚类与上分支做交叉熵损失。你可以把每个epoch后平均网络和学生网络的mAP都打印出来，就会发现平均网络在训练中比较强。
