### ISSUE TITLE
数据集找不到

### ISSUE THREAD

**Issue by kuyedie520** [chenhao2345/ABMT#6]
你好，我根据给的数据集地址并没有找到msmt17的下载地址。我自己从晚上下载后缺少list_train.txt，list_val.txt两个文件。能麻烦告诉一下链接吗？

**Comment by kuyedie520** [comment]
你好，还有一个问题就是你再训练时msmt数据集的训练集与测试集是以bounding_box_train命名还是train，我看网上有两种

**Comment by chenhao2345** [comment]
你可以从这里下载https://github.com/yxgeee/SpCL/issues/16#issuecomment-731942254

**Comment by chenhao2345** [comment]
我自己用的是MSMT17_V2版本，训练集与测试集命名是mask_train_v2, mask_test_v2。你可以根据你下载的版本改一下abmt/msmt17.py 里的命名。

**Comment by kuyedie520** [comment]
好的，MSMT17_V2跟MSMT17_V1对应的txt文件也不一样吗？还有MSMT17，这几个的txt文件都是通用的吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月26日(星期五) 下午5:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chenhao2345/ABMT] 数据集找不到 (#6)





 
我自己用的是MSMT17_V2版本，训练集与测试集命名是mask_train_v2, mask_test_v2。你可以根据你下载的版本改一下abmt/msmt17.py 里的命名。

**Comment by chenhao2345** [comment]
我当时是直接给作者发邮件要的数据集，他给我的就是V2。根据我自己的了解，V2就是V1遮了脸的版本。txt应该是通用的。

**Comment by kuyedie520** [comment]
可以加一下你的联系方式吗？你给的链接打不开，可以麻烦发给我一下吗？跪求！






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月26日(星期五) 晚上6:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chenhao2345/ABMT] 数据集找不到 (#6)





 
我当时是直接给作者发邮件要的数据集，他给我的就是V2。根据我自己的了解，V2就是V1遮了脸的版本。txt应该是通用的。

**Comment by chenhao2345** [comment]
你给我邮箱hao.chen@inria.fr发你的联系方式吧，我传给你

**Comment by kuyedie520** [comment]
你可以加我扣扣吗？现在在外面手机发邮件有点问题。扣扣号2396696832。或者你给我扣扣号我来加你------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年3月26日(星期五) 晚上6:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chenhao2345/ABMT] 数据集找不到 (#6)
