### ISSUE TITLE
关于实验结果

### ISSUE THREAD

**Issue by Mrkkew** [chenhao2345/ABMT#7]
你好，我看了一下论文实验，发现增加为3个branch后，性能会降低，论文中只是对三分支的网络结构做了简单的介绍，想问一下，做实验的时候，三个分支的时候网络的损失函数是怎么分配的呢？为什么两个分支的效果就是最好的呢？
此外，max分支的bottleneck为什么对实验性能影响这么大呢？看了一下，两个分支中的resnet最后一个block的参数应该是不共享的吧，想问一下当时做实验增加这个bottleneck提升性能的想法是什么？

**Comment by chenhao2345** [comment]
你好，谢谢关注。我在试3个分支时还是用的cross-branch的方式，即第一个分支监督第二个分支， 第二个分支监督第三个分支， 第三个分支监督第一个分支，发现结果没有提升。我的猜想是第三个分支提取的特征和前两个branch的特征重复的居多，因为我没有更多的限制。

加max分支的想法跟文中baseline MMT 加第二组teacher－student网络相同，尽量使网络抽取到更加丰富的人物特征。根据之前做有监督reid的经验，加了这个分支。

**Comment by Mrkkew** [comment]
好的好的。我还想问一个问题。看到论文中对于hard label只添加了分类损失，而三元组损失被注释掉了。想问一下，为什么hard label 的三元组损失没有作用呢？

**Comment by chenhao2345** [comment]
经过对比试验，我发现hard label 的三元组损失并不能加强我们模型的性能，就注释掉了。hard label 的三元组损失毕竟噪音比较大，soft label的三元组损失配合我们的双分支已经提供了足够强的辨别能力。
